// Generated by uniffi-bindgen-react-native
#ifdef __cplusplus
#import "react-native-zksync-sso.h"
#endif

#ifdef RCT_NEW_ARCH_ENABLED
#import "RNZksyncSsoSpec.h"

@interface ZksyncSso : NSObject <NativeZksyncSsoSpec>
#else
#import <React/RCTBridgeModule.h>

@interface ZksyncSso : NSObject <RCTBridgeModule>
#endif

@end