// Generated by uniffi-bindgen-react-native
#include "react-native-zksync-sso.h"
#include "generated/ffi.hpp"

namespace zksyncsso {
	using namespace facebook;

	uint8_t installRustCrate(jsi::Runtime &runtime, std::shared_ptr<react::CallInvoker> callInvoker) {
		NativeFfi::registerModule(runtime, callInvoker);
		return true;
	}

	uint8_t cleanupRustCrate(jsi::Runtime &runtime) {
		return false;
	}
}