// Generated by uniffi-bindgen-react-native
import installer from './NativeZksyncSso';

// Register the rust crate with Hermes
// - the boolean flag ensures this loads exactly once, even if the JS
//   code is reloaded (e.g. during development with metro).
let rustInstalled = false;
if (!rustInstalled) {
  installer.installRustCrate();
  rustInstalled = true;
}

// Export the generated bindings to the app.
// @ts-ignore
export * from './generated/ffi';

// Now import the bindings so we can:
// - intialize them
// - export them as namespaced objects as the default export.
// @ts-ignore
import * as ffi from './generated/ffi';

// Initialize the generated bindings: mostly checksums, but also callbacks.
// - the boolean flag ensures this loads exactly once, even if the JS code
//   is reloaded (e.g. during development with metro).
let initialized = false;
if (!initialized) {
  ffi.default.initialize();
  initialized = true;
}

import * as register from './passkey/register';
import * as authenticate from './passkey/authenticate';
import * as utils from './passkey/utils';

// Export the crates as individually namespaced objects.
export default {
  ffi,
  register,
  authenticate,
  utils,
};

