[workspace]
members = ["crates/*"]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2024"
rust-version = "1.85"
license = "Apache-2.0"

[workspace.dependencies]

# Alloy
alloy = { version = "0.12.5", default-features = false, features = [
    "rlp",
    "serde",
    "rpc-types",
    "signer-local",
    "reqwest",
    "contract",
    "eip712",
] }
alloy-zksync = { version = "0.12.5" }

# Http
url = "2.5.4"

# Serialization
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

# Async
tokio = { version = "1.43.0", features = ["full"] }
async-trait = "0.1"
futures = "0.3"

# Uniffi
# uniffi = { version = "0.29" }
uniffi = { git = "https://github.com/mozilla/uniffi-rs", rev = "6c3f9b2376cb4b622247e4ae94eabe8d426cc5c5" }

# Error handling
eyre = "0.6"
thiserror = "2.0.11"

# Randomness
rand = "0.9"

# Hex
hex = "0.4"

# Base64
base64-url = "3.0.0"
base64 = "0.21"

# i18n
icu = { version = "1.5.0", features = ["default", "serde", "std"] }
icu_decimal = { version = "1.5.0", features = ["default"] }
fixed_decimal = "0.5.6"
fixed = "1.28.0"
